### ISSUE TITLE
Add PRIVATE_KEY to Travis

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting-extensions/ocds-for-gpa#1]
For the draft GPA profile to build, we need to add the PRIVATE_KEY for the ocds-docs Bytemark user to https://travis-ci.org/open-contracting-extensions/ocds-for-gpa/settings

Can that be shared with me? You can use my [GPG key](https://pgp.mit.edu/pks/lookup?search=jamespetermckinney%40gmail.com&op=index) to encrypt a file, send the key via Signal or WhatsApp, or put it on the Redmine server for me to copy.

@timgdavies @duncandewhurst @Bjwebb @robredpath @kindly

**Comment by jpmckinney** [comment]
I tried setting it up on ReadTheDocs: http://ocds-for-gpa.readthedocs.io/en/latest/

The standard_theme is being used, but some includes (like theme.css) aren't present, not sure why.

I added as maintainers on ReadTheDocs bjwebb, timdavies and opendataservices.

Can you add me as a maintainer on the ocds-for-ppps project on ReadTheDocs, so that I can see its configuration?

**Comment by timgdavies** [comment]
@bjwebb Is going to look at this, with deploying to http://standard.open-contracting.org/profiles/gpa  (unless other location is preferred) so that we don't need to worry about the ReadTheDocs.

**Comment by jpmckinney** [comment]
Thanks!

**Comment by Bjwebb** [comment]
> Separately, can you add me as a maintainer on the ocds-for-ppps project on ReadTheDocs, just so I have access?

Sure thing. ReadTheDocs has its own usernames, so could I double check what yours is?

**Comment by jpmckinney** [comment]
@Bjwebb I'm jpmckinney - thanks!

Also, disregard what I said earlier – I've now decrypted the GPG message and got the value for PRIVATE_KEY.

**Comment by jpmckinney** [comment]
Cool, it now builds: http://standard.open-contracting.org/profiles/gpa/master/en/
